import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet" />
          <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap" rel="stylesheet" />
        </head>
        <body className={`${inter.className} antialiased min-h-screen flex flex-col`}>
          <Header />
          <main className="flex-1 flex flex-col">
            {children}
          </main>
          <Toaster richColors/>
          <footer className="w-full bg-purple-300 h-24 flex items-center justify-center border-t py-12 text-white">
            <p>© 2024 SpendSense. All rights reserved.</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}